#include<LiquidCrystal.h>
LiquidCrystal lcd(8,9,4,5,6,7);


void setup()

{
  
  lcd.begin(16,2);
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(0,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(1,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(2,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(3,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(4,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(5,0);
  lcd.print("-"); 
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(6,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(7,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(8,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(9,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(10,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(11,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(12,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(13,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(14,0);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(15,0);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(0,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(1,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(2,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(3,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(4,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(5,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(6,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(7,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(8,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(9,1);
  lcd.print("_");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print("."); 
  lcd.setCursor(10,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".");
  lcd.setCursor(11,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print("."); 
  lcd.setCursor(12,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print(".") ;
  lcd.setCursor(13,1);
  lcd.print("<");
  delay(500);
  lcd.clear();
  lcd.setCursor(14,1);
  lcd.print("-");
  delay(500);
  lcd.clear();
  lcd.setCursor(15,1);
  lcd.print("<");
  delay(500);

}

void loop() 

{
 

}
